[package]
name = "musiclinks_converter"
version = "0.1.0"
authors = ["David Camperos <davidapks@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.4"
